### PR TITLE
Refactoring and code styling.

### PR DESCRIPTION
**Pull request by adngdb**
@mathjazz Instead of reviewing, I went through the file locally and made changes where I saw fit. This shouldn't be breaking anything, it's just refactoring. What do you think? 

Some notable changes: 

1. I've used `Array.map` and `Array.forEach` wherever possible, instead of jQuery functions.

2. Only one `var` declaration per line.

3. I put closing brackets on new lines, I think it makes the code a lot easier to read. I like to have well-marked blocks, and dislike the `} else if () {` style, which I find harder to read. 

I'll use that knowledge to give you a better review on the actual PR next week.

### CODE REVIEW

**Comment by mathjazz** [comment]
Good move!

But it breaks the editor - none of the translations of the test project renders correctly in the editor. I always see the empty field "Value: [    ]".

There's also one `$.each()` left.

**Comment by mathjazz** [comment]
> But it breaks the editor - none of the translations of the test project renders correctly in the editor. I always see the empty field "Value: [ ]".

Pardon, that's not true! Only the plurals example breaks (Delete this downloads?).

**Comment by adngdb** [comment]
@mathjazz Problem addressed! I've kept the remaining `$.each` around because it iterates over jQuery objects, and I think that's the one case when it makes sense. What do you think?

**Comment by mathjazz** [comment]
Thanks for the update! I agree about `$.each`.

This is a big big readability improvement. I like your code style a lot!

**Pull request merged**
